version: "3"
services:
  eleventy:
    image: node:16-slim
    volumes:
      - ${PWD}/node_modules
      - ${PWD}:/home/node/app
      - ${PWD}/../text:/home/node/app/text
      - ${PWD}/../../LICENSE.md:/home/node/app/text/extra/LICENSE.md
    working_dir: /home/node/app
    # environment:
    #   - DEBUG=Eleventy*
    ports:
      - 8080:8080
    command: /bin/bash -c "npm install && npx eleventy --watch --serve"
