name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Set up Java 17
      uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
        
    - name: Build with Gradle
      run: ./gradlew assembleDebugUnitTest -Dpre-dex=false
      
    - name: Run Unit Tests
      run: ./gradlew testDebugUnitTest -Dpre-dex=false -q
